### ISSUE TITLE
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :    polygon edge not found

### ISSUE THREAD

**Issue by alakin4** [gkaramanis/tidytuesday#2]
Hej Georgios,

I am trying to re-create your code for  the sf tree map and I get this error:

``` r
Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
  polygon edge not found
In addition: Warning messages:
1: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "JetBrains Mono Bold"
2: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "JetBrains Mono Bold"
3: In grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  :
  no font could be found for family "JetBrains Mono Bold"
Error in grDevices::dev.off() :
```
Did you encounter it at some point?

**Comment by gkaramanis** [comment]
Hej! 

Oh yes, I've seen it myself before more than once. It's because you don't have the JetBrains font.
You can delete the `family = "JetBrains Mono"` in the script, or delete it, or install the font 😄

**Comment by alakin4** [comment]
Wow!! I would have spent ages on this. Thank you very much. I ended up downloading the JetBrains font too; it seems nice.

**Comment by gkaramanis** [comment]
You’re welcome! I’ve been there, this message still gets me sometimes!
